version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ecom
      POSTGRES_USER: ecom
      POSTGRES_PASSWORD: ecompwd
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ecom -d ecom"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: ./backend
    env_file:
      - .env.example
    volumes:
      - images_data:/data/images
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  mock-mpesa:
    build: ./mock-mpesa
    env_file:
      - .env.example
    ports:
      - "8090:8090"
    depends_on:
      - api

  web:
    build: ./frontend
    env_file:
      - .env.example
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE=http://localhost:8080
    command: ["sh", "-c", "npm install && npm run dev -- --host"]

volumes:
  db_data: {}
  images_data: {}
